spring:
  h2:
    console:
      enabled: true

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    url: jdbc:h2:./loop
    username: sa
    #generate-unique-name: false
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.H2Dialect

server:
  port: 8088

springdoc:
  swagger-ui:
    path: /documentation
    enabled: true
